# Site Settings
title: Messcafe
email: leetusman@gmail.com
description: >
  A site for putting info and resources to the virtual art community Messlife
baseurl: ""
url: "http://localhost:4000"
twitter_username: 2sman2sman
github_username:  lee2sman
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
